language: python
python:
  - "2.7"
install: "pip install -U git+https://github.com/ConsenSys/EthOnDocs.git"
script: 
  - "python newSpecGenerator.py"
  - "cp 404.html ${TRAVIS_BUILD_DIR}/spec"
  - "touch ${TRAVIS_BUILD_DIR}/spec/.nojekyll"
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: "${TRAVIS_BUILD_DIR}/spec"
  target_branch: gh-pages
  fqdn: ethon.consensys.net
  on:
    branch: master

